name: Deploy Local

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Stop and remove any existing container
      - name: Stop and remove existing Docker container
        run: |
          docker stop my-app || true
          docker rm my-app || true

      - name: Pull the latest changes from the repository
        run: git pull origin main

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app .

      # Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d --name my-app -p 3000:3000 my-app
